#
# Creates a secret to hold the base64 encoded user and password for accessing Azure File Share mounts within k8s pods.
#

apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: $base64_user
  azurestorageaccountkey: $base64_password
